plugins {
    id 'com.android.application'
}

android {
    namespace 'de.codevoid.mfrn'
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "de.codevoid.mfrn"
        minSdk 34
        targetSdk 35
        versionCode 1
        versionName "0.1.0"

        def gitHash = providers.exec {
            commandLine 'git', 'rev-parse', '--short=7', 'HEAD'
        }.standardOutput.asText.get().trim()
        buildConfigField "String", "GIT_HASH", "\"${gitHash}\""
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.core:core:1.13.1'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
